"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Plus, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { toast } from "sonner"; // Use sonner instead of useToast

export function NewAnalysisForm() {
    const [url, setUrl] = useState("");
    const [loading, setLoading] = useState(false);
    const router = useRouter();
    const supabase = createClient();

    const [showManual, setShowManual] = useState(false);
    const [manualText, setManualText] = useState("");

    const handleAnalyze = async () => {
        if (!url && !manualText) return;
        setLoading(true);

        try {
            // 1. Get current user (anonymous or logged in)
            const { data: { user } } = await supabase.auth.getUser();

            let userId = user?.id;
            if (!userId) {
                // MVP: Use the Guest User ID created via backend
                userId = "0d93271a-2865-458a-8191-7a3b5934b52c";
            }

            let transcript = manualText;

            // Only fetch if not using manual input or if manual text is short
            if (!transcript || transcript.length < 100) {
                toast.loading("Extracting interview text...", { id: "transcript" });
                const transcriptRes = await fetch("/api/transcript", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ url })
                });

                if (!transcriptRes.ok) {
                    toast.dismiss("transcript");
                    setShowManual(true);
                    throw new Error("Unable to extract transcript automatically. Please paste it manually below.");
                }
                const data = await transcriptRes.json();
                transcript = data.transcript;

                if (data.isAutoGenerated) {
                    toast.success("Auto-generated captions detected!", { id: "transcript" });
                } else {
                    toast.success("Transcript extracted!", { id: "transcript" });
                }
            }

            // 2. Call Backend API
            const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/analyze`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    youtube_url: url || "MANUAL_INPUT",
                    user_id: userId,
                    video_title: "Pending...",
                    company: "Custom Analysis",
                    role: "Executive",
                    target_person: "Speaker",
                    transcript_text: transcript
                }),
            });

            if (!response.ok) {
                throw new Error("Failed to start analysis");
            }

            const data = await response.json();

            toast.success("Analysis started!");
            router.push(`/analysis/${data.analysis_id}`);

        } catch (error: any) {
            console.error(error);
            toast.error(error.message || "Failed to start analysis. Please try again.");
        } finally {
            setLoading(false);
        }
    };

    const handleDemo = async () => {
        setLoading(true);
        try {
            const { data: { user } } = await supabase.auth.getUser();
            let userId = user?.id;

            if (!userId) {
                userId = "0d93271a-2865-458a-8191-7a3b5934b52c";
            }

            const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/analyze`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    youtube_url: "DEMO_MODE",
                    user_id: userId,
                    video_title: "Executive Presence Demo",
                    company: "Demo Corp",
                    role: "Executive",
                    target_person: "Speaker"
                }),
            });

            if (!response.ok) throw new Error("Failed to start demo");

            const data = await response.json();
            toast.success("Demo Analysis Loaded!");
            router.push(`/analysis/${data.analysis_id}`);

        } catch (error) {
            console.error(error);
            toast.error("Failed to load demo.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="flex flex-col gap-4 w-full max-w-2xl mx-auto">
            <div className="flex flex-col gap-4 p-6 bg-white rounded-2xl border border-slate-200 shadow-sm transition-all hover:shadow-md">
                <div className="space-y-2">
                    <h3 className="text-sm font-semibold text-slate-900 uppercase tracking-wider">Start New Analysis</h3>
                    <p className="text-sm text-slate-500">Enter a YouTube URL or use the Demo mode to see how it works.</p>
                </div>

                <div className="flex gap-2">
                    <Input
                        placeholder="Paste YouTube URL here..."
                        className="h-12 text-sm border-slate-200 focus:border-emerald-500 focus:ring-emerald-500 bg-slate-50/50"
                        value={url}
                        onChange={(e) => setUrl(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && handleAnalyze()}
                    />
                    <Button size="lg" className="h-12 px-6 bg-slate-900 hover:bg-slate-800 text-white font-medium transition-all active:scale-95 disabled:opacity-50" onClick={handleAnalyze} disabled={loading}>
                        {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}
                        {loading ? "Analyzing..." : "Analyze"}
                    </Button>
                </div>

                {showManual && (
                    <div className="mt-4 animate-in fade-in slide-in-from-top-2 duration-300">
                        <textarea
                            placeholder="Paste the transcript text here manually if YouTube extraction failed..."
                            className="w-full h-32 p-3 text-sm border rounded-lg border-amber-200 bg-amber-50/30 focus:border-amber-500 focus:ring-amber-500 outline-none resize-none transition-all"
                            value={manualText}
                            onChange={(e) => setManualText(e.target.value)}
                        />
                        <div className="flex justify-between items-center mt-2">
                            <p className="text-[10px] text-amber-600 font-medium italic">YouTube is blocking automated access. Manual paste is required.</p>
                            <Button variant="ghost" size="sm" className="h-7 text-xs text-slate-400 hover:text-slate-600" onClick={() => setShowManual(false)}>Hide</Button>
                        </div>
                    </div>
                )}

                <div className="pt-2 border-t border-slate-100 flex items-center justify-between">
                    <span className="text-[10px] text-slate-400 font-medium uppercase tracking-widest">Try the system:</span>
                    <Button variant="link" className="text-xs text-emerald-600 font-semibold p-0 h-auto hover:text-emerald-700" onClick={handleDemo}>
                        Run Demo Analysis →
                    </Button>
                </div>
            </div>
        </div>
    );
}
