// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhwujmtwnsyjvanlcprs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impod3VqbXR3bnN5anZhbmxjcHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMTkwNzQsImV4cCI6MjA2ODg5NTA3NH0.a80u1JJJVKNtWVLik97oNkdgQeVYtWKH50RFyCjnevM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});